version: "3.9"

services:
  database:
    image: postgres
    container_name: database
    restart: always
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: fin_api
    volumes:
      - pgdata:/data/postgres
  database_test:
    image: postgres
    container_name: database_test
    restart: always
    ports:
      - 5433:5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: fin_api_test
    volumes:
      - pgdata_test:/data/postgres
  app:
    build: .
    container_name: fin_api
    restart: always
    ports:
      - 3333:3333
    volumes:
      - .:/usr/app
    links:
      - database
    depends_on:
      - database
volumes:
  pgdata:
    driver: local
  pgdata_test:
    driver: local
